version: '3.8'

services:
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - gym-network
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: cs108
#      MYSQL_USER: root
      MYSQL_PASSWORD: freeuni2023
      MYSQL_ROOT_PASSWORD: freeuni2023
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gym-network

  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gym-network

  eureka:
    image: itsgigim/dockerhub:eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
    networks:
      - gym-network

  gymapp:
    image: itsgigim/dockerhub:latest
    container_name: gymapp
    depends_on:
      - mysql-db
      - eureka
      - activemq
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS: false
      DATA_FILE: data.json
      PASSWORD_LENGTH: 10
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cs108
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: freeuni2023
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus,health
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      SECRET_KEY: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      SPRING_APPLICATION_NAME: gymApp
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USERNAME: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
      SPRING_ACTIVEMQ_PACKAGES_TRUST_ALL: true
      WORK_HOURS_QUEUE: Workhours.queue
      SPRING_ACTIVEMQ_REDELIVERY_POLICY_MAXIMUM_REDELIVERIES: 3
      SPRING_ACTIVEMQ_DEAD_LETTER_QUEUE_NAME: DLQ
    networks:
      - gym-network

  work-hours:
    image: itsgigim/dockerhub:workhours
    container_name: work-hours
    depends_on:
      - mongo-db
      - eureka
      - activemq
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: totalDuration
      SERVER_PORT: 8080
      SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS: false
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/local
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
      SECRET_KEY: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USERNAME: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
      SPRING_ACTIVEMQ_PACKAGES_TRUST_ALL: true
      WORK_HOURS_QUEUE: Workhours.queue
      RETRIEVE_WORK_HOURS_QUEUE: Retrieve.queue
      SPRING_ACTIVEMQ_REDELIVERY_POLICY_MAXIMUM_REDELIVERIES: 3
      SPRING_ACTIVEMQ_DEAD_LETTER_QUEUE_NAME: DLQ
    networks:
      - gym-network

volumes:
  mysql_data:
  mongo_data:

networks:
  gym-network: