package com.example.taskspring.utils;

public enum Endpoint {
    LOGIN,
    CHANGE_PASSWORD,
    REGISTER_TRAINEE,
    RETRIEVE_TRAINEE,
    MODIFY_TRAINEE,
    REMOVE_TRAINEE,
    UPDATE_TRAINER_LIST,
    TRAINEE_RETRIEVE_TRAININGS_LIST,
    TRAINEE_MODIFY_ACTIVE_STATUS,
    RETRIEVE_UNASSIGNED_TRAINERS,
    CREATE_TRAINING,
    REGISTER_TRAINER,
    RETRIEVE_TRAINER,
    MODIFY_TRAINER,
    TRAINER_RETRIEVE_TRAININGS_LIST,
    TRAINER_MODIFY_ACTIVE_STATUS,
    TRAINING_TYPES
}
